---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name:
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - libssh2-php
          - php5-mcrypt
          - mysql-server-5.6
          - python-mysqldb
          - php5-mysql
        state: latest
      become: yes # Indica usuario root 

    - name: 'Cria o banco MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present

    - name: 'Cria o usuario do MySQL'
      mysql_user:
        login_user: root
        name: wordpressuser
        password: 12345
        priv: 'wordpress_db.*:ALL' # Tem todos privilegios para o banco wordpress_db
        state: present